### ISSUE TITLE
Awesome, Mani!! :) 

### ISSUE THREAD

**Issue by DostoievskiF** [infinyte7/Anki-Occlusion#1]
I confess that I was not following the project for a while.  It's been a while since I found out that you had changed the repository.  xD

**Dude ... I'm very happy with the evolution of this application. :)** 

I have a suggestion - I've already sent so many others... I think I'm even filling your patience.
 Is it possible to create an automatic zoom adjustment system for images in the application?  So that it adjusts itself to the screen, without the need to keep selecting the zoom function.

What happens when I import an image:
![Screenshot_20210302-223800_Anki Image Occlusion](https://user-images.githubusercontent.com/72423426/109741635-35139800-7bac-11eb-9f7a-05614adb5f8a.jpg)

 How should the automatic adjustment to the screen size be when importing the image:
![Screenshot_20210302-223822_Anki Image Occlusion](https://user-images.githubusercontent.com/72423426/109741642-39d84c00-7bac-11eb-9e20-d3184940229a.jpg)

It would also be really cool for you to "register" with Brave Creators, I think it would be easier to contribute to the project - because dollar is a heavy for my local currency :(.

![image](https://user-images.githubusercontent.com/72423426/109739771-e7496080-7ba8-11eb-91ee-7910880bcd49.png)

https://creators.brave.com/

**Comment by krmanik** [comment]
Try latest release. The image will auto fit to screen width size.

Thanks, I will view this.
https://creators.brave.com/
