### ISSUE TITLE
Hello Mani

### ISSUE THREAD

**Issue by medmedmedic** [infinyte7/Anki-Occlusion#2]
Hello Mani , Its been really great to see you browser based image occlusion , I am a medical school Anatomy prof from south of India. I find SRS very useful in Anatomy need your help for testing out this in medical students. 

My apologies for posting it here in issues. How do i connect to you ? 

drmathewsbox@gmail.com

**Comment by krmanik** [comment]
I have added my email id to profile.
 infinyte01@gmail.com

I have sent you mail.

**Comment by medmedmedic** [comment]
Thank you mani,
