### ISSUE TITLE
Bugs and Suggestions

### ISSUE THREAD

**Issue by DostoievskiF** [infinyte7/Anki-Occlusion#4]
**Hey, Mani! :)**
Your Anki Occlusion has been a very important tool for me.

I would like to comment a few things about the Android app:

1) It would be nice if there was an option to reset that count of cards added to Anki, after we put in the clozes. Sometimes I want to make clozes on another image, so I need to close and open the app to reset the count.

2) BUG: sometimes one of the clozes ends up duplicating, which is pretty annoying. When we put all the clozes on an image and click on the ✅, more cards are created than intended, and this ends up being quite annoying since I have to erase all the clozes one by one to find the one that was duplicated; then I still have to go to AnkiDroid to delete all the cards "contaminated" by that duplicate cloze, to add them back later, hoping that the duplicate cloze has been deleted. :(

3) Another suggestion (much less important than the second): it would be nice if we could choose which deck (among the ones I have) to allocate the created cards.

### **Thank you so much for your amazing work, Mani! Because of this sensational tool you created, I boosted my grades in the tests I've been taking.**

**Comment by krmanik** [comment]
I will implement it from scratch. The next update will be better than previous version in terms of card generation, shape selection and delete and more..

**Comment by DostoievskiF** [comment]
### **Thank you so much, Mani! Your tool helped me A LOT to pass the Medicine course in my region, at the university I wanted.**

I take this opportunity to give you one more suggestion - this one is completely secondary to the previous ones.
I think it would be interesting if there was an improvement in the function of adding texts over the cloze. I mean, if you had, for example how to place a text on each rectangle of a cloze - even on each of the cloze combined.

**Do you have any predictions when the new update will come out? xD**

**Comment by krmanik** [comment]
The card generation is improved. Now, no duplicate cards will be generated. Also delete function is improved.
Try it and provide feedback so the app can be improved more in next updates.

Download from Release page or F-Droid. (May be it take time to be processed on F-Droid)

**Comment by DostoievskiF** [comment]
### **Excellent, Mani! I tested it. :)**

I point out 3 things:
1) BUG: when I tap "Draw" to create some cloze, the rectangle doesn't form between the two edges I touched. If I tap a point and then the bottom right diagonal, it creates the rectangle correctly; however, if I touch a point and then any other diagonal, the rectangle forms elsewhere in the image - even though it conforms to the desired aspect ratio.
2) BUG: the Delete function got MUCH, MUCH better. There's only one problem: it doesn't erase combined clozes. :(
3) Great!! I tried several things that were doubling the clozes! They aren't duplicating anymore, which is amazing!! xD

**Comment by krmanik** [comment]
These features has been added. Some other features need improvement. May be next released will be delayed.
Current latest version is v1.4.5. 
Download from Release page or F-Droid. (May be it take time to be processed on F-Droid)

**Comment by DostoievskiF** [comment]
### **I installed the new version and tested it! :)** 
All previous bugs have been perfectly fixed.
It's exceptional, Mani! I'm glad you keep maintaining Occlusion better and better!

**Comment by DostoievskiF** [comment]
**Hey, Mani! I found another bug yesterday. :(**

If you put a cloze and touch it to adjust its size, it won't can be included in a combined cloze; and some selected cloze to be combined can't be reverted.

There is a video showing the problem.
https://www.youtube.com/watch?v=AsFYGWrwK_c

**Comment by krmanik** [comment]
I understood the bug, I will update in next release.

**Comment by DostoievskiF** [comment]
**Thank you so much, Mani! Your helpfulness makes me very happy! :)**

**Comment by krmanik** [comment]
Hi,
There are features added. Please try it and provide feedback. Thanks
* Add images using Camera capture
* Crop selected images in editor window
* Add images using Share option from other apps

Download from Release page or F-Droid. (May be it take time to be processed on F-Droid)

**Comment by DostoievskiF** [comment]
### **Hi, Mani!**  
I'm really glad you fixed the bugs I found. :) 
I tested the latest version you released! Here are my considerations: 
1) the connection to the camera is working perfectly. 
2) the possibility of uploading a photo to the app through the sharing option is awesome. 😊
3) image cropping is slightly problematic: the cropping rectangle could, for example, automatically fit the image size so that we could adjust the area to be cropped from the original image - analogous to conventional smartphone galleries. 
The essentials are working exceptionally. 😀

**Comment by krmanik** [comment]
The crop feature will be improved in next update.

**Comment by DostoievskiF** [comment]
**All right, Mani?** :)
I would like to leave you some more suggestions: 
1) The possibility of adding text in "Combine Cloze" mode.

**Comment by krmanik** [comment]
It will be updated in next release.
