### ISSUE TITLE
cannot create combined clozes

### ISSUE THREAD

**Issue by HarryPott3r** [infinyte7/Anki-Occlusion#5]
I cannot create combined clozes. I activate the selection tool, but the clozes are not selected when I tap.
Whats wrong?
I am using a Galaxy A5 2017.
![Screenshot_20210726-181918_Anki Image Occlusion](https://user-images.githubusercontent.com/88002807/127061487-6a8e178d-c074-41a7-a3f4-51b57df2cb3f.jpg)

**Comment by krmanik** [comment]
These features has been updated. Current latest version is v1.4.6.
Download from Release page or F-Droid. (May be it take time to be processed on F-Droid)

**Comment by HarryPott3r** [comment]
Thank you so much! 🙏
