### ISSUE TITLE
Drawing over the image

### ISSUE THREAD

**Issue by HarryPott3r** [infinyte7/Anki-Occlusion#8]
**I had posted to another colleague's issue.**

Infinyte7, is it possible to add a draw over image mode in your app? I use a tablet in my studies. My suggestion is simple, although I have no idea how complex it is to implement something like this.

It would be awesome if I could freely write/draw over the added image in such a way that my scribbles were just in front of the cards.
Workflow example:

1. I add an image to the app.
2. Place the occlusions.
3. I write (with the tablet pen, in my case) over the image and even over the occlusions, like a question or an arrow/figure...
4. When creating the cards and going to answer them, my scribbles would only appear on the front of the card.
It would also be awesome if there was a way to minimally customize the pen stroke (thickness mainly).

Thank you very much for your attention, my friend. I would like to financially support the project with some money that I have been collecting in cryptocurrencies. Do you have any wallet? This new function would help me a lot, without a shadow of a doubt.

**Comment by krmanik** [comment]
I understood the feature. It will take some time to figure out implementation. 

I have implemented for adding text. But it will used as question and answer.

Is it the feature?
Let's say array, hand written text or any thing that needs to permanently shown on question and answer then my implementation approach
1. Add image
2. Click to draw / add handwritten text
3. Then save, it add extra svg image that will present on question and answer. It will not show / hide.

**Comment by HarryPott3r** [comment]
My idea would be for the extra svg image to appear only in front.  However, I think it would be really awesome if there was a setting that let me select where I want it to appear:
- only in front;
 - just in back;
 - front and back.
 
 Here is an outline:

**Comment by HarryPott3r** [comment]
The following example refers to the option where the extra SVG image with the squiggles would only appear in front.  A pencil tool (with some customization options) and eraser to create the layer.

**FRONT SIDE:**
![Screenshot_20210930-015218_AnkiDroid](https://user-images.githubusercontent.com/88002807/135389553-6e9c959a-6e62-4d68-9fe2-8baf10995b58.jpg)


**BACK SIDE:**
![Screenshot_20210930-015229_AnkiDroid](https://user-images.githubusercontent.com/88002807/135389618-dad4a288-820f-4c94-b691-71911740f09f.jpg)
